services:

  mariadb:
    container_name: mariadb
    build: ./mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build: ./wordpress
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: ./nginx
    env_file: .env
    restart: on-failure

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/fbelotti/data/wordpress"

  mariadb:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/fbelotti/data/mariadb"

networks:
  inception:
    driver: bridge